language: node

before_install:
 - chmod +x ./scripts/*
 - ./scripts/before_install.sh

before_script:

script: ./scripts/build.sh

after_success:
 - ./scripts/after_success.sh
after_failure:
- ./scripts/after_failure.sh

env:
  global:
    - MAKER_KEY=bE23wcpswHaGhx-lE7I599
    - YELLOW=FFFF00
    - RED=FF0000
    - GREEN=00FF00