language: node

before_install:
 - chmod +x ./scripts/*
 - curl https://maker.ifttt.com/trigger/build_event/with/key/$MAKER_KEY?value=$YELLOW

before_script:

script: ./scripts/build.sh

after_success:
 - curl https://maker.ifttt.com/trigger/build_event/with/key/$MAKER_KEY?value=$GREEN
after_failure:
- curl https://maker.ifttt.com/trigger/build_event/with/key/$MAKER_KEY?value=$RED

env:
  global:
    - MAKER_KEY=bE23wcpswHaGhx-lE7I599
    - YELLOW=FFFF00
    - RED=FF0000
    - GREEN=00FF00